### PROGRAMMING ASSIGNMENT 2 - Numpy

#### Normalization Problem

In [2]:
import numpy as np

In [8]:
X = np.random.random((5,5))

In [22]:
mean = X.mean()

In [24]:
std = X.std()

In [80]:
Z = (X - mean) / std

In [82]:
print("Original Matrix:\n", X)

Original Matrix:
 [[0.72480725 0.03867405 0.17773795 0.62407131 0.45849654]
 [0.39064809 0.73046588 0.49311497 0.68549487 0.55024703]
 [0.09210944 0.77120057 0.69192793 0.72208122 0.99543377]
 [0.75869288 0.26874554 0.43913705 0.11568715 0.30398433]
 [0.9871721  0.36987108 0.46504686 0.49085036 0.42432174]]


In [84]:
print ("Normalized Matrix:\n ", Z)

Normalized Matrix:
  [[ 0.83900821 -1.85096391 -1.30576654  0.44407487 -0.20505784]
 [-0.47105639  0.86119276 -0.06933695  0.68488478  0.15464819]
 [-1.64147147  1.02089232  0.71010547  0.82832084  1.89999431]
 [ 0.97185617 -0.94897302 -0.28095634 -1.54903551 -0.81082001]
 [ 1.86760458 -0.55251228 -0.17937746 -0.07821533 -0.33903948]]


In [90]:
np.save('X_normalized.npy', X)

In [94]:
data = np.load('X_normalized.npy')
data

array([[0.72480725, 0.03867405, 0.17773795, 0.62407131, 0.45849654],
       [0.39064809, 0.73046588, 0.49311497, 0.68549487, 0.55024703],
       [0.09210944, 0.77120057, 0.69192793, 0.72208122, 0.99543377],
       [0.75869288, 0.26874554, 0.43913705, 0.11568715, 0.30398433],
       [0.9871721 , 0.36987108, 0.46504686, 0.49085036, 0.42432174]])

#### Divisible by 3 Problem

In [99]:
import numpy as np

In [101]:
A = np.arange(1,101).reshape(10,10)**2

In [103]:
Y = A[A % 3 == 0]

In [105]:
print("Original Matrix: \n", A)

Original Matrix: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [107]:
print("Divisible by 3 Matrix: \n", Y)

Divisible by 3 Matrix: 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [109]:
np.save('div_by_3.npy', Y)

In [111]:
data = np.load('div_by_3.npy')
data

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])