### PROGRAMMING ASSIGNMENT 2 - Numpy

## Problem 1: Normalization Problem

Normalization is a fundamental preprocessing technique in data analytics that involves two main steps:

1. **Centering** :  Subtracting the mean of the data.
2. **Scaling** :  Dividing by the standard deviation of the data.

This process helps to standardize the data, making it easier to analyze or input into machine learning models. Mathematically, normalization can be expressed as:

`Z = (𝑋−x̄) / 𝜎`

where:
- *X*  is the original data,
- *x̄* is the mean of the data,
- *𝜎* is the standard deviation of the data.

#### Task:
- Create a random 5 x 5 NumPy array and store it in a variable `X`.
- Normalize the array `X` by centering and scaling it.
- Save the normalized array to a file named `X_normalized.npy`.

#### Example:
To help understand the process, consider the following example:
- If `X = [1, 2, 3, 4, 5]`, then the mean x̄ = `3.0` and standard deviation 𝜎 = `1.4142135623730951`.
- The normalized values *Z* would be `[-1.41421356 -0.70710678  0.  0.70710678  1.41421356]`.

#### Expected Output:
- The normalized array should have a mean of approximately 0 and a standard deviation of 1.

Use Python's `.mean()` and `.std()` functions to calculate the mean and standard deviation element-wise.


In [3]:
import numpy as np

In [4]:
X = np.random.random((5,5))

In [108]:
mean = X.mean()

0.587515648324913

In [110]:
std = X.std()

0.2457216174354048

In [7]:
Z = (X - mean) / std

In [58]:
print("Original Matrix:\n\n", X)

Original Matrix:

 [[0.84953291 0.67058687 0.71519203 0.3455978  0.10195362]
 [0.59790012 0.51007256 0.5348443  0.19135817 0.96362612]
 [0.82586004 0.51988642 0.33519051 0.55776571 0.48713626]
 [0.85942038 0.28095948 0.851745   0.40814051 0.22918372]
 [0.83048146 0.97877931 0.5975819  0.85109004 0.59400596]]


In [60]:
print ("Normalized Matrix:\n\n ", Z)

Normalized Matrix:

  [[ 1.06631749  0.33807045  0.51959766 -0.98452002 -1.97606557]
 [ 0.04226113 -0.31516595 -0.21435374 -1.6122207   1.53063648]
 [ 0.96997731 -0.275227   -1.02687401 -0.1210717  -0.40850858]
 [ 1.106556   -1.2475751   1.07531994 -0.7299933  -1.45828408]
 [ 0.98878484  1.5923046   0.04096609  1.07265448  0.02641327]]


In [10]:
np.save('X_normalized.npy', X)

In [11]:
data = np.load('X_normalized.npy')
data

array([[0.84953291, 0.67058687, 0.71519203, 0.3455978 , 0.10195362],
       [0.59790012, 0.51007256, 0.5348443 , 0.19135817, 0.96362612],
       [0.82586004, 0.51988642, 0.33519051, 0.55776571, 0.48713626],
       [0.85942038, 0.28095948, 0.851745  , 0.40814051, 0.22918372],
       [0.83048146, 0.97877931, 0.5975819 , 0.85109004, 0.59400596]])

## Problem 2: Divisible by 3 Problem

In this problem, you will create a 10 x 10 NumPy array `A` that contains the squares of the first 100 positive integers.

### Task:
1.   Create a 10 x 10 ndarray `A` such that:
- The first row contains the squares of the integers from 1 to 10.
- The second row contains the squares of the integers from 11 to 20, and so on.
   
2.   Find all elements in this ndarray that are divisible by 3.
3.   Save the resulting array to a file named `div_by_3.npy`.

### Example:
               A = 
     [1    4    ⋯   81    100
      ⋮     ⋮    ⋱    ⋮      ⋮
      ⋮     ⋮    ⋱    ⋮      ⋮ 
      ⋮     ⋮    ⋱    ⋮      ⋮
    8281  8464  ⋯  9801  10000]


### Finding Elements Divisible by 3:
- To determine which elements are divisible by 3, you can use the modulus operator `%` in Python.
- For example, if `A = [1, 4, 9, 16]`, elements divisible by 3 are `[9]`.

### Expected Output:
- A 1D array of elements from `A` that are divisible by 3, saved as `div_by_3.npy`.

In [13]:
import numpy as np

In [14]:
A = np.arange(1,101).reshape(10,10)**2

In [15]:
Y = A[A % 3 == 0]

In [16]:
print("Original Matrix: \n", A)

Original Matrix: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [17]:
print("Divisible by 3 Matrix: \n", Y)

Divisible by 3 Matrix: 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [18]:
np.save('div_by_3.npy', Y)

In [19]:
data = np.load('div_by_3.npy')
data

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])