### PROGRAMMING ASSIGNMENT 2 - Numpy

## Problem 1: Normalization Problem

Normalization is a fundamental preprocessing technique in data analytics that involves two main steps:

1. **Centering** :  Subtracting the mean of the data.
2. **Scaling** :  Dividing by the standard deviation of the data.

This process helps to standardize the data, making it easier to analyze or input into machine learning models. Mathematically, normalization can be expressed as:

`Z = (𝑋−x̄) / 𝜎`

where:
- *X*  is the original data,
- *x̄* is the mean of the data,
- *𝜎* is the standard deviation of the data.

#### Task:
- Create a random 5 x 5 NumPy array and store it in a variable `X`.
- Normalize the array `X` by centering and scaling it.
- Save the normalized array to a file named `X_normalized.npy`.

#### Example:
To help understand the process, consider the following example:
- If `X = [1, 2, 3, 4, 5]`, then the mean x̄ = `3.0` and standard deviation 𝜎 = `1.4142135623730951`.
- The normalized values *Z* would be `[-1.41421356 -0.70710678  0.  0.70710678  1.41421356]`.

#### Expected Output:
- The normalized array should have a mean of approximately 0 and a standard deviation of 1.

Use Python's `.mean()` and `.std()` functions to calculate the mean and standard deviation element-wise.


In [116]:
import numpy as np
#import the numpy library

In [118]:
X = np.random.random((5,5))
#generate random values for a 5x5 array

In [120]:
mean = X.mean()
#calculate the mean of array X

In [122]:
std = X.std()
#calculate the standard deviation of array X

In [124]:
Z = (X - mean) / std
#normalize array X by inputting the data above

In [126]:
print("Original Matrix:\n\n", X)
#show the original matrix X

Original Matrix:

 [[0.75737883 0.18731579 0.43147408 0.86873342 0.83872992]
 [0.92182079 0.21946684 0.00177271 0.88466284 0.47948613]
 [0.11233381 0.37958051 0.07114482 0.58481923 0.74394847]
 [0.48048881 0.29543701 0.30282077 0.16961256 0.94667521]
 [0.69785238 0.61962671 0.49635285 0.47100172 0.67345306]]


In [128]:
print ("Normalized Matrix:\n\n ", Z)
#show the normalized matrix Z

Normalized Matrix:

  [[ 0.89943735 -1.13571979 -0.26406095  1.29697947  1.1898653 ]
 [ 1.4865044  -1.02093875 -1.79811902  1.35384841 -0.09265525]
 [-1.40340968 -0.44932391 -1.55045669  0.28338983  0.8514902 ]
 [-0.08907563 -0.74972096 -0.72336053 -1.19892131  1.57523604]
 [ 0.68692455  0.40765451 -0.03244011 -0.12294507  0.5998176 ]]


In [130]:
np.save('X_normalized.npy', X)
#save array X to a file named "X_normalized.npy"

In [132]:
data = np.load('X_normalized.npy')
data
#load the saved array file

array([[0.75737883, 0.18731579, 0.43147408, 0.86873342, 0.83872992],
       [0.92182079, 0.21946684, 0.00177271, 0.88466284, 0.47948613],
       [0.11233381, 0.37958051, 0.07114482, 0.58481923, 0.74394847],
       [0.48048881, 0.29543701, 0.30282077, 0.16961256, 0.94667521],
       [0.69785238, 0.61962671, 0.49635285, 0.47100172, 0.67345306]])

## Problem 2: Divisible by 3 Problem

In this problem, you will create a 10 x 10 NumPy array `A` that contains the squares of the first 100 positive integers.

### Task:
1.   Create a 10 x 10 ndarray `A` such that:
- The first row contains the squares of the integers from 1 to 10.
- The second row contains the squares of the integers from 11 to 20, and so on.
   
2.   Find all elements in this ndarray that are divisible by 3.
3.   Save the resulting array to a file named `div_by_3.npy`.

### Example:
               A = 
     [1    4    ⋯   81    100
      ⋮     ⋮    ⋱    ⋮      ⋮
      ⋮     ⋮    ⋱    ⋮      ⋮ 
      ⋮     ⋮    ⋱    ⋮      ⋮
    8281  8464  ⋯  9801  10000]


### Finding Elements Divisible by 3:
- To determine which elements are divisible by 3, you can use the modulus operator `%` in Python.
- For example, if `A = [1, 4, 9, 16]`, elements divisible by 3 are `[9]`.

### Expected Output:
- A 1D array of elements from `A` that are divisible by 3, saved as `div_by_3.npy`.

In [114]:
import numpy as np
#import the numpy library

In [140]:
A = np.arange(1,101).reshape(10,10)**2
#create a 10x10 array with the squares of the first 100 positive integers

In [15]:
Y = A[A % 3 == 0]
#determine if the element is divisible by 3

In [134]:
print("Original Matrix: \n", A)
#print the original matrix A

Original Matrix: 
 [1 2 3 4 5]


In [136]:
print("Divisible by 3 Matrix: \n", Y)
#print the divisible by 3 matrix Y

Divisible by 3 Matrix: 
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [18]:
np.save('div_by_3.npy', Y)
#save array Y to a file named "div_by_3.npy"

In [138]:
data = np.load('div_by_3.npy')
data
#load the saved array file

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])